### ISSUE TITLE
추가설명 필요할 듯

### ISSUE THREAD

**Issue by Gumball12** [ycj1212/kotlin#1]
아래와 같은 내용이 있는데

![image](https://user-images.githubusercontent.com/28308362/73688114-b03b1e00-470e-11ea-9a5b-498e081bc68c.png)

동적 타입 지정 언어마냥 사용해도 코틀린 컴파일러 자체에서 정적 타입 바인딩을 시켜준다는 의미인 것 같은데, 글만 봐서는 코틀린이 동적 타입 바인딩을 지원한다는 말로 들림

**Comment by ycj1212** [comment]
수정하였습니다

**Comment by ycj1212** [comment]
수정하였습니다

**Comment by Gumball12** [comment]
^-^
